config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pics

  root "pics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

  before_action :find_pic, only: [:show, :edit, :update, :destroy]

  def index
    @pics = Pic.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pic = current_user.pics.build
  end

  def create
    @pic = current_user.pics.build(pic_params)

    if @pic.save
      redirect_to @pic, notice: "Yesss! It was posted!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: "Congrats! Pic was updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end

private

  def pic_params
    params.require(:pic).permit(:title, :description)
  end

  def find_pic
    @pic = Pic.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instasham</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <a class="navbar-brand" > <%= link_to 'Instasham', root_path %></a>
          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sham It", new_pic_path %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <%else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |name, msg| %>
      <div class: "alert alert-info">
        <%= msg %>
      </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pics/_form.html.erb
<%= simple_form_for @pic, html: {multipart: true} do |f| %>
  <% if @pic.errors.any? %>
  <section id="errors" >
  <h2> <%= pluralize(@pic.errors.count, "error") %> prohibited this image from being saved: </h2>
    <ul>
      <% @pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
    <% end %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control' }  %>
  </div>
  <%= f.button :submit, class: 'btn btn-info'  %>
<% end %>

app/views/pics/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">.col-md-8 .col-md-offset-2</div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h1> Edit Pic </h1>
        </div>
          <div class="panel-body">
            <%= render 'form' %>
          </div>
      </div>
  </div>
</div>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
<h2> <%= link_to pic.title, pic %> </h2>
<% end %>

app/views/pics/new.html.erb
  <div class="row">
    <div class="col-md-8 col-md-offset-2">.col-md-8 .col-md-offset-2</div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h1> Post Pic </h1>
        </div>
        <div class="container">
            <div class="panel-body">
              <%= render 'form' %>
            </div>
        </div>
      </div>
  </div>
</div>

app/views/pics/show.html.erb
<h1> <%= @pic.title %> </h1>
<p> <%= @pic.description %> </p>
<p> Pic by <%= @pic.user.email %> </p><br>

<%= link_to 'Back', root_path %>
<%= link_to 'Edit', edit_pic_path %>
<%= link_to 'Delete', pic_path, method: :delete, data: { confirm: "Are you sure? "} %>